version: "2"
services:
  chatsrv:
    build: ../../srv
    container_name: "chatsrv"
    image: chatsrv:dev
    volumes:
      - ../../srv:/app
    ports:
      - 3001:3001
    # networks:
    #   - app-network

  chatweb:
    build: ../../web
    container_name: "chatweb"
    image: chatweb:dev
    volumes:
      - ../../srv:/app
    ports:
      - 3000:80
    depends_on:
      - chatsrv
    # networks:
    #   - app-network
# networks:
#   app-network:
#     driver: bridge
